version: '3'

services:
  app:
    build: docker/app
    volumes:
      - ${VOLUME_APP}:/var/www/html/app/
    environment:
      - ENV=dev
    ports:
      - "${PORT_APP}:80"
  mysql:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./.data/db:/var/lib/mysql:rw
    ports:
        - "${PORT_MYSQL}:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
